### ISSUE TITLE
Is this app ready for testing?

### ISSUE THREAD

**Issue by Christian4561** [joanlopez/connecta4-html5#1]
I found this app and launched it from [RawGit ] (https://rawgit.com/joanlopez/connecta4-html5/develop/index.html)and it didn't really do anything. Is it ready for testing? label:question

**Comment by joanlopez** [comment]
My purpose is to make a functional basis for the game and then extend it with improvements and new platforms.

The problem is that the basis is not ended yet. This is why I have no files on master branch, because i'm developing.

At the moment it does not check if any player wins and some other basic things.

I will release a version to master branch when I finish the game basis.

**Comment by Christian4561** [comment]
Ok.
